### ISSUE TITLE
Malformed request sent when connecting to peers

### ISSUE THREAD

**Issue by boreq** [ssbc/go-muxrpc#9]
On connection go-muxrpc sends the following request to peers:

    {
        "name": "manifest",
        "args": [],
        "type": "async"
    }

This request is malformed as per the protocol guide request name is a list of strings:

>The name is a list of strings. For a top-level procedure like createHistoryStream the list only has one element: ["createHistoryStream"].

https://ssbc.github.io/scuttlebutt-protocol-guide/#request-format

This means that the request should instead have the following form:

    {
        "name": ["manifest"],
        "args": [],
        "type": "async"
    }

Therefore it is possible that clients which reject connections from peers which send malformed requests will not be able to communicate with projects which use go-muxrpc.

**Comment by cryptix** [comment]
I wish that was the case in practice.. a Manifest Call like that is allowed as a first request to bootstrap the set of possible calls as a first interaction.

Back when I encountered this I didn't find a better what if introducing this semantics then allow for an opaque string then as well. PR welcome.

There is some gory background and details like the initial JS bootstrapping PR in this issue: https://github.com/ssb-js/secret-stack/pull/71

**Comment by boreq** [comment]
In that case we should try documenting this in the protocol guide. I don't really feel like I know enough to do this but I will try getting up to speed using this link and maybe I will manage to create some docs for it. That being said the fact that the `name` field uses a different type out of the sudden is quite awkward in my opinion.

**Comment by decentral1se** [comment]
Thanks for your documentation work @boreq. Much appreicated!
